services:
  - type: web
    name: cid-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: GROQ_API_KEY
        sync: false